from urllib import response
from flask import Flask, render_template

app = Flask(__name__)

shoujo = [{"title": "namaikizakari/cheeky brat", "genre": "high school romance", "summary":"yuki machida, a 2nd year hs student, is the manager of the school's basketball team. during the welcoming ceremoney she meets sho naruse, her junior one year younger than her, a cheeky student who joins the basketball team. every day yuki's patience is tested with naruse's constant advances.", "tropes": "older fl, athlete x manager, mature fl, childish ml, he fell first"},
          {"title" : "kimi ni todoke/from me to you", "genre" : "high school romance, slice of life", "summary":"sawako kuronuma has always been misunderstood due to her appearance with rumors around school reporting that she can see ghosts and curse people. however, despite her ominous appearance, she is actually a sweet unassuming girl who wants to be helpful. when popular boy, shota kazehaya, starts to talk to her everything changes and she finds herself in a new world.", "tropes":"misunderstood fl, popular ml, he fell first, childhood friends (secound couple)"},
          {"title" : "wotakoi: love is hard for otaku", "genre" : "rom-com", "summary":"namuri momose is an office lady who hides her fujoshi lifestyle, and hirotaka nifuji, her childhood friend and co-worker is a game otaku. narumi attempts to keep the fact that she's an otaku a secret while hirotaka doesn't care. the two seem perfect for each other, but love is difficult for otaku.", "tropes":"office romance, childhood friends, energetic fl x quiet ml"},
          {"title" : "orange", "genre" : "romance, slice of life", "summary":"naho takamiya, a 2nd year hs student receives a letter sent from herself 10 years into the future. her future self asks her to prevent her biggest regrets, which has something to do with the new transfer student, kakeru naruse. while skeptic at first, she eventually starts to believe the letters as they accurately predict events.", "tropes":"angst, message from the future, tragic past"},
          {"title" : "l-dk", "genre" : "rom-com, slice of life", "summary":"shusei kugayama, the prince of his hs has a reputation of turning down confessions from admiring girls. aoi nishimori takes offence after he turns down her best friend. later that day, aoi is greeted by her new apartment neight, who turns out to be shusei. after a kitchen fire ruins his apartment, shusei moves into aoi's flat, and romance blooms from there.", "tropes":"forced proximity, living together, popular ml"},
          {"title" : "ao haru ride", "genre" : "highschool romance", "summary":"futaba yoshioka is a 16-year-old high school student who reconnects with her first love, kou tanaka, after he moved away in middle school. she used to be popular with the boys, but girls ostracized her out of jealousy, so now she acts unfeminine to fit in with her female friends.", "tropes":"the one that got away, quiet fl, first love, hard-to-read ml"},
          {"title" : "okuremashite seishun", "genre" : "rom-com, slice of life", "summary":"wataba is a 20-year-old college student who yearns for youth. on halloween she dresses up in her school uniform and ends up on a date with a hs boy. but in fact, the boy is also a college student. in order to make wakaba's dream come true, she is asked to continue going out with him on school uniform dates", "tropes":"fluff, cosplay/school uniform, mistaken identity"},
          {"title" : "kanojo to kare no kankei/her relationship with him", "genre" : "highschool rom-com, slice of life", "summary":"kaho, who has never had a boyfriend before, wanted to have a boy-girl relationship. takumi, who wanted a girlfriend, just so happened to be talking about it in front of her, and so they get together! a sweet, coming-of-age, love story between two inexperienced students.", "tropes":"fluff, straightforward fl, first-time dating"}
          ]
@app.route("/api")
def api():
